### ISSUE TITLE
Interferes with Palo Alto Firewall

### ISSUE THREAD

**Issue by OSUso** [cloudtracer/ThreatPinchLookup#24] opened 2017-02-16 08:41 UTC
When using Palo Alto firewall management interface and monitoring you can usually click source and destination IP addresses and they get included into the query. That stops working.
Can I disable ThreatPinch on particular pages?

**Comment by cloudtracer** [comment] 2017-02-16 10:28
Absolutely, check out the filtering rules section in the wiki. Just add the page to your website deny list.

https://github.com/cloudtracer/ThreatPinchLookup/wiki/1.4-Filtering-Rules

I'll see if I can reproduce the issue as well to figure out why it's happening.

**Comment by OSUso** [comment] 2017-02-16 11:49
Thank you,
I should have checked the Wiki.
thanks
OS

**Comment by cloudtracer** [comment] 2017-02-18 14:43
No problem OSUso.  You are the first to open an interference issue since the public release, and filtering rules are something we probably don't highlight all that well. 

I was able to reproduce problem with the Palo Alto interface, and the issue is a complicated one that I've seen with other vendor web dashboards. Essentially they are referencing DOM elements as data fields for their javascript code and the span elements our injector code uses to wrap observables breaks that code.  Its definitely the wrong way to reference data, but unfortunately common enough that I've seen it before on other web management interfaces.

I have some ideas on how to solve this, but its going to require some extensive testing. Stay tuned, I'll let you know when I roll out a fix.

**Comment by cloudtracer** [comment] 2017-04-13 11:26
Haven't forgotten about this one, its just required some serious changes to how the popovers are created. The fix is in, and should be released in a few days after its been battle tested a bit.

The new method shouldn't cause any problems like this in the future as it doesn't rely on wrapping DOM elements.

**Comment by cloudtracer** [comment] 2017-05-14 18:19
Should be fixed in v2.0.0, being pushed to the store now.

**Closed by cloudtracer** 2017-05-14 18:19 UTC
